In [219]:
import numpy as np
import pandas as pd 

from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler


In [220]:
dfs = [pd.read_csv('~/Downloads/batter_' + str(yr) + '.csv') for yr in range(2009, 2020)]

In [221]:
type(dfs)

list

In [222]:
type(dfs[0])

pandas.core.frame.DataFrame

In [247]:
np.isnan(dfs[0]['試合'])

0     False
1     False
2     False
3     False
4     False
      ...  
56    False
57    False
58    False
59    False
60    False
Name: 試合, Length: 61, dtype: bool

In [56]:
#セ・リーグ、パ・リーグの両MVPがどちらとも投手だった、2014年の行は削除し、分析したい2019年のデータも入れない。

In [223]:
whole_year_array = np.concatenate((dfs[0], dfs[1], dfs[2], dfs[3], dfs[4], dfs[6], dfs[7], dfs[8], dfs[9]), axis = 0)

In [224]:
whole_year_array

array([['田中 賢介', '日本ハム', 144, ..., 17, 0, 0],
       ['井端 弘和', '中日', 144, ..., 8, 13, 0],
       ['中島 裕之', '西武', 144, ..., 0, 17, 0],
       ...,
       ['中島 卓也', '日本ハム', 132, ..., 22, 4, 0],
       ['野間 峻祥', '広島', 126, ..., 4, 2, 0],
       ['松山 竜平', '広島', 124, ..., 0, 10, 0]], dtype=object)

In [225]:
type(whole_year_array)

numpy.ndarray

In [226]:
df_whole_year = pd.DataFrame(data = whole_year_array, columns = dfs[0].columns)

In [210]:
df_whole_year

選手名   チーム   試合  打席数   打数   安打 本塁打  打点  盗塁  四球  死球   三振  犠打 併殺打 MVP
0     田中 賢介  日本ハム  144  680  575  163   3  49  31  79   5  105  17   0   0
1     井端 弘和    中日  144  657  569  174   5  39  13  72   6   66   8  13   0
2     中島 裕之    西武  144  648  560  173  22  92  20  75  10  113   0  17   0
3     片岡 易之    西武  139  646  588  153  13  58  51  36   7   72  12   8   0
4      栗山 巧    西武  140  643  569  152  12  57  18  53  10  106   8   9   0
..      ...   ...  ...  ...  ...  ...  ..  ..  ..  ..  ..  ...  ..  ..  ..
501  梅野 隆太郎    阪神  132  455  386  100   8  47   5  39   1   67  28   6   0
502   島内 宏明    楽天  103  453  394  115  11  53  11  47   6   45   3  10   0
503   中島 卓也  日本ハム  132  449  391  102   1  23  29  35   0   88  22   4   0
504   野間 峻祥    広島  126  447  405  116   5  46  17  30   6   69   4   2   0
505   松山 竜平    広島  124  446  397  120  12  74   2  42   2   46   0  10   0

[506 rows x 15 columns]

In [227]:
df_whole_year.columns

Index(['選手名', 'チーム', '試合', '打席数', '打数', '安打', '本塁打', '打点', '盗塁', '四球', '死球',
       '三振', '犠打', '併殺打', 'MVP'],
      dtype='object')

In [228]:
X_train = df_whole_year[['試合', '打席数', '打数', '安打', '本塁打', '打点', '盗塁', '四球', '死球',
       '三振', '犠打', '併殺打']]

Y_train = df_whole_year[['MVP']]
Y_train = Y_train.astype('int')

X_test = dfs[10][['試合', '打席数', '打数', '安打', '本塁打', '打点', '盗塁', '四球', '死球',
       '三振', '犠打', '併殺打']]

Y_test = dfs[10][['MVP']]
Y_test = Y_test.astype('int')

In [233]:
model = LogisticRegression()
model.fit(X_train, Y_train)

/Users/takezomisono/Desktop/python_program/ml_env/lib/python3.7/site-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/takezomisono/Desktop/python_program/ml_env/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [234]:
model.predict(X_test)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [231]:
print('正解率(train):{:.3f}'.format(model.score(X_train, Y_train)))

正解率(train):0.978


In [214]:
print('正解率(test):{:.3f}'.format(model.score(X_test, Y_test)))

正解率(test):0.950


In [130]:
model.predict(X_train)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,

In [239]:
#標準化処理 
sc = StandardScaler()
sc.fit(X_train)
X_train_std = sc.transform(X_train)
X_test_std = sc.transform(X_test)

model = LogisticRegression()
model.fit(X_train_std, Y_train)


/Users/takezomisono/Desktop/python_program/ml_env/lib/python3.7/site-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [240]:
model.predict(X_test_std)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [241]:
model.score(X_train_std, Y_train)

0.9782608695652174

In [242]:
model.score(X_test_std, Y_test)

0.95

In [238]:
dfs[10][14:15]

選手名 チーム   試合  打席数   打数   安打  本塁打  打点  盗塁   四球  死球  三振  犠打  併殺打  MVP
14  鈴木 誠也  広島  140  612  499  167   28  87  25  103   7  81   0    3    0